import { StyleSheet, Text, View } from "react-native";
import { useGetStats } from "@ody/api-client";
import type { GetStats200PopularItemsItem } from "@ody/api-client";
import { PageLayout } from "../components/layout/PageLayout";
import { Card } from "../components/ui/Card";
import { Skeleton } from "../components/ui/Skeleton";
import { Table, type Column } from "../components/ui/Table";
import { colors, fontSize, fontWeight, spacing } from "../design-system/tokens";
import { formatPrice } from "../utils/format";

// ── Popular items table columns ───────────────────────────────────────────────

const POPULAR_COLUMNS: Column<GetStats200PopularItemsItem>[] = [
  {
    key: "name",
    header: "Item",
    render: (r) => <Text style={styles.cell}>{r.name}</Text>,
  },
  {
    key: "orderCount",
    header: "Orders",
    width: 100,
    render: (r) => <Text style={styles.cell}>{r.orderCount}</Text>,
  },
];

// ── Page ─────────────────────────────────────────────────────────────────────

export default function DashboardHome() {
  // useGetStats() is generated by Orval from GET /stats.
  // It returns { data, isLoading, isError } — standard React Query shape.
  const { data, isLoading } = useGetStats();

  return (
    <PageLayout title="Dashboard">
      {/* KPI cards */}
      <View style={styles.grid}>
        <StatCard
          label="Orders today"
          value={data ? String(data.totalOrders) : undefined}
          loading={isLoading}
        />
        <StatCard
          label="Revenue today"
          value={data ? formatPrice(data.totalRevenue) : undefined}
          loading={isLoading}
        />
        <StatCard
          label="Pending orders"
          value={data ? String(data.pendingOrders) : undefined}
          loading={isLoading}
          highlight={data ? data.pendingOrders > 0 : false}
        />
      </View>

      {/* Popular items */}
      <View style={styles.tableSection}>
        <Text style={styles.sectionTitle}>Top menu items</Text>
        <Card padding={0}>
          <Table
            columns={POPULAR_COLUMNS}
            data={data?.popularItems ?? []}
            keyExtractor={(r) => r.id}
            loading={isLoading}
            emptyMessage="No order data yet"
          />
        </Card>
      </View>
    </PageLayout>
  );
}

// ── Stat card ────────────────────────────────────────────────────────────────

function StatCard({
  label,
  value,
  loading,
  highlight = false,
}: {
  label: string;
  value?: string;
  loading: boolean;
  highlight?: boolean;
}) {
  return (
    <Card style={styles.card}>
      {loading || value === undefined ? (
        <Skeleton height={36} width={80} />
      ) : (
        <Text style={[styles.statValue, highlight && styles.statHighlight]}>{value}</Text>
      )}
      <Text style={styles.statLabel}>{label}</Text>
    </Card>
  );
}

const styles = StyleSheet.create({
  grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[4], marginBottom: spacing[8] },
  card: { minWidth: 160, flex: 1, gap: spacing[2] },
  statValue: { fontSize: fontSize["3xl"], fontWeight: fontWeight.bold, color: colors.stone[900] },
  statHighlight: { color: colors.primary[600] },
  statLabel: { fontSize: fontSize.sm, color: colors.stone[500] },
  tableSection: { gap: spacing[3] },
  sectionTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.semibold, color: colors.stone[700] },
  cell: { fontSize: fontSize.sm, color: colors.stone[800] },
});
