// Hand-written TypeScript types shared across the frontend and backend.
// This is for things NOT covered by the generated API client:
// design token types, UI state enums, shared constants, etc.
//
// API data types (Order, MenuItem, Customer, etc.) come from @ody/api-client,
// which is generated by Orval from the OpenAPI spec. Do not duplicate them here.

export {};
